openapi: 3.0.1
info:
  title: Flights Search API
  description: Finds up to date and detailed flight tickets
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /get-flights:
    get:
      operationId: getFlights
      summary: Get a list of flights matching the specified criteria
      description: Returns a list of flights, optionally filtered by providing the departure airport, destination airport, departure date, and connections as query parameters
      parameters:
        - name: departure
          in: query
          description: The departure airport to search in
          required: true
          schema:
            type: string
        - name: destination
          in: query
          description: The destination airport to search in
          required: true
          schema:
            type: string
        - name: date
          in: query
          description: The departure date
          required: false
          schema:
            type: string
        - name: connections
          in: query
          description: The number of connections
          required: false
          schema:
            type: integer
        - name: class
          in: query
          description: The class of the flight
          required: false
          schema:
            $ref: '#/components/schemas/FlightClassesEnum'
      responses:
        '200':
          description: OK - Returns a list of flights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
components:
  schemas:
    FlightClassesEnum:
      type: string
      enum:
        - economy
        - business
        - first
    Flight:
      type: object
      properties:
        airline:
          type: string
          description: The airline operating the flight
        flight_number:
          type: string
          description: The flight number
        departure_airport:
          type: string
          description: The departure airport of the flight
        destination_airport:
          type: string
          description: The destination airport of the flight
        departure_time:
          type: string
          description: The depature time of the flight
        arrival_time:
          type: string
          description: The arrival time of the flight
        connections:
          type: integer
          description: The number of connections
        class:
          type: string
          description: The class of the flight ticket
          items:
            $ref: '#/components/schemas/AmenitiesEnum'